### ISSUE TITLE
Interleaved2of5 not recognized

### ISSUE THREAD

**Issue by mlundela** [asposebarcode/Aspose_BarCode_Java#27]
![barcode-horizontal](https://user-images.githubusercontent.com/16946/50911227-b7bac580-142f-11e9-8e6f-90209f43f8cf.jpg)

The example barcode is not recognized.

**Comment by mlundela** [comment]
Works if I increase resolution.

**Comment by ahmad-chishti** [comment]
It is good to know that your issue has been resolved. Please keep using our API and in case of any other query, please feel free to contact us.
